"""
Details at:
-----------
https://freesound.org/docs/api/analysis_docs.html

EXAMPLE
-------
https://freesound.org/apiv2/search/text/?query=guitar&fields=id%2Cname%2Canalysis&descriptors=lowlevel.spectral_complexity
"""

class FreeSoundDescriptors():
    # Metadata
    METADATA_VERSION = "metadata.version"
    # Low Level
    LOW_LEVEL_SPECTRAL_COMPLEXITY = "lowlevel.spectral_complexity"
    LOW_LEVEL_SILENCE_RATE_20DB = "lowlevel.silence_rate_20dB"
    LOW_LEVEL_ERB_BANDS = "lowlevel.erb_bands"
    LOW_LEVEL_AVERAGE_LOUDNESS = "lowlevel.average_loudness"
    LOW_LEVEL_SPECTRAL_RMS = "lowlevel.spectral_rms"
    LOW_LEVEL_SPECTRAL_KURTOSIS = "lowlevel.spectral_kurtosis"
    LOW_LEVEL_BARKBANDS_KURTOSIS = "lowlevel.barkbands_kurtosis"
    LOW_LEVEL_SCVALLEYS = "lowlevel.scvalleys"
    LOW_LEVEL_SPECTRAL_SPREAD = "lowlevel.spectral_spread"
    LOW_LEVEL_PITCH = "lowlevel.pitch"
    LOW_LEVEL_DISSONANCE = "lowlevel.dissonance"
    LOW_LEVEL_SPECTRAL_ENERGYBAND_HIGH = "lowlevel.spectral_energyband_high"
    LOW_LEVEL_GFCC = "lowlevel.gfcc"
    LOW_LEVEL_SPECTRAL_FLUX = "lowlevel.spectral_flux"
    LOW_LEVEL_SILENCE_RATE_30DB = "lowlevel.silence_rate_30dB"
    LOW_LEVEL_SPECTRAL_CONTRAST = "lowlevel.spectral_contrast"
    LOW_LEVEL_SPECTRAL_ENERGYBAND_MIDDLE_HIGH = "lowlevel.spectral_energyband_middle_high"
    LOW_LEVEL_BARKBANDS_SPREAD = "lowlevel.barkbands_spread"
    LOW_LEVEL_SPECTRAL_CENTROID = "lowlevel.spectral_centroid"
    LOW_LEVEL_PITCH_SALIENCE = "lowlevel.pitch_salience"
    LOW_LEVEL_SILENCE_RATE_60DB = "lowlevel.silence_rate_60dB"
    LOW_LEVEL_SPECTRAL_ENTROPY = "lowlevel.spectral_entropy"
    LOW_LEVEL_SPECTRAL_ROLLOFF = "lowlevel.spectral_rolloff"
    LOW_LEVEL_BARKBANDS = "lowlevel.barkbands"
    LOW_LEVEL_SPECTRAL_ENERGYBAND_LOW = "lowlevel.spectral_energyband_low"
    LOW_LEVEL_BARKBANDS_SKEWNESS = "lowlevel.barkbands_skewness"
    LOW_LEVEL_PITCH_INSTANTANEOUS_CONFIDENCE = "lowlevel.pitch_instantaneous_confidence"
    LOW_LEVEL_SPECTRAL_ENERGYBAND_MIDDLE_LOW = "lowlevel.spectral_energyband_middle_low"
    LOW_LEVEL_SPECTRAL_STRONGPEAK = "lowlevel.spectral_strongpeak"
    LOW_LEVEL_START_FRAME = "lowlevel.startFrame"
    LOW_LEVEL_SPECTRAL_DECREASE = "lowlevel.spectral_decrease"
    LOW_LEVEL_STOP_FRAME = "lowlevel.stopFrame"
    LOW_LEVEL_MFCC = "lowlevel.mfcc"
    LOW_LEVEL_SPECTRAL_ENERGY = "lowlevel.spectral_energy"
    LOW_LEVEL_SPECTRAL_FLATNESS_DB = "lowlevel.spectral_flatness_db"
    LOW_LEVEL_FREQUENCY_BANDS = "lowlevel.frequency_bands"
    LOW_LEVEL_ZEROCROSSINGRATE = "lowlevel.zerocrossingrate"
    LOW_LEVEL_SPECTRAL_SKEWNESS = "lowlevel.spectral_skewness"
    LOW_LEVEL_HFC = "lowlevel.hfc"
    LOW_LEVEL_SPECTRAL_CREST = "lowlevel.spectral_crest"
    # Rhythm
    RHYTHM_FIRST_PEAK_BPM = "rhythm.first_peak_bpm"
    RHYTHM_ONSET_TIMES = "rhythm.onset_times"
    RHYTHM_BEATS_COUNT = "rhythm.beats_count"
    RHYTHM_BEATS_LOUDNESS = "rhythm.beats_loudness"
    RHYTHM_FIRST_PEAK_SPREAD = "rhythm.first_peak_spread"
    RHYTHM_SECOND_PEAK_WEIGHT = "rhythm.second_peak_weight"
    RHYTHM_BPM = "rhythm.bpm"
    RHYTHM_BPM_INTERVALS = "rhythm.bpm_intervals"
    RHYTHM_ONSET_COUNT = "rhythm.onset_count"
    RHYTHM_SECOND_PEAK_SPREAD = "rhythm.second_peak_spread"
    RHYTHM_BEATS_LOUDNESS_BAND_RATIO = "rhythm.beats_loudness_band_ratio"
    RHYTHM_SECOND_PEAK_BPM = "rhythm.second_peak_bpm"
    RHYTHM_ONSET_RATE = "rhythm.onset_rate"
    RHYTHM_BEATS_POSITION = "rhythm.beats_position"
    RHYTHM_FIRST_PEAK_WEIGHT = "rhythm.first_peak_weight"
    # Tonal
    TONAL_HPCP_ENTROPY = "tonal.hpcp_entropy"
    TONAL_CHORDS_SCALE = "tonal.chords_scale"
    TONAL_CHORDS_NUMBER_RATE = "tonal.chords_number_rate"
    TONAL_KEY_STRENGTH = "tonal.key_strength"
    TONAL_CHORDS_PROGRESSION = "tonal.chords_progression"
    TONAL_KEY_SCALE = "tonal.key_scale"
    TONAL_CHORDS_STRENGTH = "tonal.chords_strength"
    TONAL_KEY_KEY = "tonal.key_key"
    TONAL_CHORDS_CHANGES_RATE = "tonal.chords_changes_rate"
    TONAL_CHORDS_COUNT = "tonal.chords_count"
    TONAL_HPCP_CREST = "tonal.hpcp_crest"
    TONAL_CHORDS_HISTOGRAM = "tonal.chords_histogram"
    TONAL_CHORDS_KEY = "tonal.chords_key"
    TONAL_TUNING_FREQUENCY = "tonal.tuning_frequency"
    TONAL_HPCP_PEAK_COUNT = "tonal.hpcp_peak_count"
    TONAL_HPCP = "tonal.hpcp"

    # SFX
    SFX_TEMPORAL_DECREASE = "sfx.temporal_decrease"
    SFX_INHARMONICITY = "sfx.inharmonicity"
    SFX_PITCH_MIN_TO_TOTAL = "sfx.pitch_min_to_total"
    SFX_TC_TO_TOTAL = "sfx.tc_to_total"
    SFX_DER_AV_AFTER_MAX = "sfx.der_av_after_max"
    SFX_PITCH_MAX_TO_TOTAL = "sfx.pitch_max_to_total"
    SFX_TEMPORAL_SPREAD = "sfx.temporal_spread"
    SFX_TEMPORAL_KURTOSIS = "sfx.temporal_kurtosis"
    SFX_LOGATTACKTIME = "sfx.logattacktime"
    SFX_TEMPORAL_CENTROID = "sfx.temporal_centroid"
    SFX_TRISTIMULUS = "sfx.tristimulus"
    SFX_MAX_DER_BEFORE_MAX = "sfx.max_der_before_max"
    SFX_STRONGDECAY = "sfx.strongdecay"
    SFX_PITCH_CENTROID = "sfx.pitch_centroid"
    SFX_DURATION = "sfx.duration"
    SFX_TEMPORAL_SKEWNESS = "sfx.temporal_skewness"
    SFX_EFFECTIVE_DURATION = "sfx.effective_duration"
    SFX_MAX_TO_TOTAL = "sfx.max_to_total"
    SFX_ODDTOEVENHARMONICENERGYRATIO = "sfx.oddtoevenharmonicenergyratio"
    SFX_PITCH_AFTER_MAX_TO_BEFORE_MAX_ENERGY_RATIO = "sfx.pitch_after_max_to_before_max_energy_ratio"